### ISSUE TITLE
Acting on utilitarianism

### ISSUE THREAD

**Issue by worldsaround** [tlon-team/utilitarianism-es#15]
1) Saqué "zapatillas" porque sólo se usa en tal sentido en la Argentina. Puse "zapatos" en consideración de la aceptación del término en todo el ámbito hispoanoamericano.

2) "por lejos" está desaconsejado por el *Panhispánico*.

3) En algún lugar vi que introducías el nombre de las secciones (después del localizados sec.) en castellano. Yo siempre lo introduzco en inglés. Quizá lo hacías porque parece más lógico que así sea si la obra se refiere a algún post de los que estamos traduciendo. Puede ser?

**Comment by benthamite** [comment]
:+1:
